#!/usr/bin/env python3
"""
CannyForge + LangGraph: Minimal Quickstart

Shows the 3-line integration and what CannyForge injects before each LLM call.

    forge = CannyForge()
    middleware = CannyForgeMiddleware(forge)
    agent = create_react_agent(model, tools, pre_model_hook=middleware.before_model)

Requirements: pip install langgraph langchain-openai
              Set LLM_API_KEY (and optionally LLM_BASE_URL) in .env
"""

import logging
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv()

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

from cannyforge import CannyForge
from cannyforge.adapters.langgraph import CannyForgeMiddleware
from cannyforge.knowledge import Rule, RuleType, Condition, ConditionOperator, Action

# Silence noisy loggers so only our print() output shows
for _name in ("httpx", "httpcore", "openai", "langgraph", "langchain",
              "CannyForge", "Knowledge", "Skills", "Tools", "Learning",
              "MockCalendarMCP", "WebSearchAPI"):
    logging.getLogger(_name).setLevel(logging.WARNING)

# ── Step 1: Set up tools ─────────────────────────────────────────────────────
try:
    from langgraph.prebuilt import create_react_agent
    from langchain_openai import ChatOpenAI
    from langchain_core.tools import tool
    HAS_LANGGRAPH = True
except ImportError:
    HAS_LANGGRAPH = False

if not HAS_LANGGRAPH:
    print("Install langgraph + langchain-openai first:")
    print("  pip install langgraph langchain-openai")
    sys.exit(1)


@tool
def calculate(expression: str) -> str:
    """Evaluate a math expression like 2+2 or 100/3."""
    return f"Result: {eval(expression, {'__builtins__': {}}, {})}"

@tool
def search_web(query: str) -> str:
    """Search the web for information on any topic."""
    return f"Results for: {query}"

@tool
def read_file(path: str) -> str:
    """Read a file from disk given its path."""
    return f"Contents of {path}"

@tool
def run_command(cmd: str) -> str:
    """Run a shell command like ls, ps, or grep."""
    return f"Output: {cmd}"

@tool
def send_message(to: str, body: str) -> str:
    """Send a message to a person with a given body text."""
    return f"Sent to {to}: {body}"

TOOLS = [calculate, search_web, read_file, run_command, send_message]

# ── Step 2: Create LLM ───────────────────────────────────────────────────────
api_key = os.environ.get("LLM_API_KEY") or os.environ.get("OPENAI_API_KEY")
if not api_key:
    print("Set LLM_API_KEY in .env")
    sys.exit(1)

llm_kwargs = {"model": os.environ.get("MODEL_FAST", "deepseek-chat"),
              "api_key": api_key, "temperature": 0}
base_url = os.environ.get("LLM_BASE_URL")
if base_url:
    llm_kwargs["base_url"] = base_url
llm = ChatOpenAI(**llm_kwargs)

# ── Step 3: The 3-line integration ───────────────────────────────────────────
forge = CannyForge(llm_provider=None)
forge.reset()
# Clear any pre-loaded bundled rules so we only see what we add below
forge.knowledge_base.rules_by_skill.clear()

middleware = CannyForgeMiddleware(forge, skill_name="tool_use")

# In production, rules are generated by CannyForge's learning cycle from
# observed errors. Here we add one directly to show the injection mechanism.
#
# This rule fires on every request and injects a SystemMessage warning
# that the LLM sees before picking a tool.
wrong_tool_rule = Rule(
    id="rule_wrong_tool_demo",
    name="Prevent WrongTool (learned)",
    rule_type=RuleType.PREVENTION,
    conditions=[
        # Always true — this warning applies to all tool-selection requests
        Condition("context.has_required_params", ConditionOperator.EQUALS, True),
    ],
    actions=[
        Action("append", "context.warnings",
               "STOP: In previous runs, the wrong tool was selected for math "
               "tasks. Before calling a tool, re-read the user's request and "
               "match the primary action verb to the correct tool."),
    ],
    confidence=0.9,
    source_error_type="WrongToolError",
)
forge.knowledge_base.add_rule("tool_use", wrong_tool_rule)

agent = create_react_agent(llm, TOOLS, pre_model_hook=middleware.before_model)

# ── Step 4: Run tasks and show what CannyForge injects ────────────────────
TASKS = [
    "What's 42 * 13?",
    "Search for LangGraph documentation",
    "Read the README.md file",
]

print("\n" + "=" * 60)
print("  CannyForge + LangGraph Quickstart")
print("=" * 60)

print("\n  Integration (3 lines):")
print("    forge = CannyForge()")
print("    middleware = CannyForgeMiddleware(forge)")
print("    agent = create_react_agent(llm, tools,")
print("        pre_model_hook=middleware.before_model)")

rules = forge.knowledge_base.get_rules("tool_use")
print(f"\n  Rules loaded: {len(rules)}")
for r in rules:
    for a in r.actions:
        if a.target in ("context.warnings", "context.suggestions"):
            print(f"    {r.name}:")
            print(f"      \"{a.value}\"")

print(f"\n  Running {len(TASKS)} tasks:")
for i, task in enumerate(TASKS, 1):
    print(f"\n  [{i:2d}/{len(TASKS)}] Task: \"{task}\"")

    # Show what CannyForge injects before the LLM sees the message
    preview = middleware.before_model({"messages": [{"content": task}]})
    injected = False
    for msg in preview.get("messages", []):
        content = msg.get("content", "") if isinstance(msg, dict) else getattr(msg, "content", "")
        if "[CANNYFORGE]" in content:
            injected = True
            print("  Injected SystemMessage:")
            for line in content.split("\n"):
                print(f"    {line}")
    if not injected:
        print("  (no rules matched)")

    # Run the real agent
    print("  Calling agent...", end="", flush=True)
    result = agent.invoke({"messages": [("user", task)]})
    tool_picked = None
    for msg in result.get("messages", []):
        if hasattr(msg, "tool_calls") and msg.tool_calls:
            tool_picked = msg.tool_calls[0]["name"]
            break
    if tool_picked:
        print(f" -> {tool_picked}")
    else:
        print(" -> (no tool call)")
print("\n" + "=" * 60 + "\n")
